# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - cmake --version
  - echo %NUMBER_OF_PROCESSORS% 

clone_depth: 50

version: '{build}'

platform:
  - x64

configuration:
  - Release

environment:
  #MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  priv_key:
    secure: Hv2V0BTJ/4Vr3np0B6sK2N93nzR6pijKETJJsKce5LrR3u0DdSK29mzB0+57oyC5G8zzhnD9FOD0URjYTSmtrXVu+MIFTytGfjdVLUnig4Cbf3NTVzQkl78HqViacWWApcgWxYnNubhU8LT+G6fj/nYqR99Ok238Q8CQTPHCrcddCkczDMz5xm5rpK95EY6cMpLqEkxHLJkUJjWC7GhoY0vRbcPcbn8PubjxKSwMbzYCSyfG2stMMyp/V7sVIJHCoYxHxzRK9qu81nFBrtgRmKQZM+OGmtbB9tt6wQyxAC3zzG0YRw/KuAqiPhepONBFN7szPlhBCYyeDBlgrqZgymAqsDaRUY9S2Hs71rGyusRo3z+VINPs6ujCVx42id9qHI6lOIRyifev1uWfleEvvu6j+MjGiA8tK9AO6JTWUWfdrIjrWWqyY23GoDuw1t4NKt8AYaGnDyAUemmHVaQgvRuJawt4iLivK4dFC97mLQI1exVr7yTtGuZpaXm+SRdTWtt588T0bIh4kI68vMIVIoGJonScuZ01fMDWdVq0m5fKcYSRLvki2V/JUmVBzfu4XTUVgBWdRIv3jkSa/GnU/Jf97CbeFE5ct4hVQyRkbK8Uhv9Xd95LGAijM9bdXoIP9M310MjwQ8bqqjwsMufc24kEci7g/bEn8tu4mjrf/Lb1lr69m7DwluxgLU9NvKqUbwQvoj4UiF7ea4/jBGE6zP3uK45NauIFjD+2tt33OyeYCzbKh7PiZ8QcS+R9XCXbYSqxruH4xC3pHsVRzLPB0Lqhnsg8qjal5D2L8LRwyYP4GvKQ03IYB2ZAT8z5sTYab6Go1ntqBuY/dc09uLXR6HLD19kDUPf/I2IRGJtDRHrPaZvK3jPxeUMAoAiMG6Mq1pyriPf2TX99KOoZFaHDWQGGSo06r1kfaQkTyjDLkji+vECUo+OK1GwyOqV35dnX4ZKj0sWRzzIk5f0p9RACy4IZ/vfeHTCpaJXqE07E7f+wlgDh+14a/he6JsjrSE0CROUWVLe1MQnPBVhJjU4uLwcvpY/OX/D0wrS3dtlL+YeKgIz/RnqHaNm1glaV36eDitt6SIixC3HMtGO6GvbPU9L8bOH40FDKlmS9DSugynRk07i+ZF9vibeBQpteCZyWgH4AcSH+09lHhw4rA6VdDZQto4Fjx2Zm+ksvCH0IjHUrSPc+8fZRFmY/N6MQ5RI0pOy/tie358/BzfnUEopYWbiSzDbRuTNe95eOPWq6ps6BRboYO1I/fgsVooHvRIsfAeddNxnV+b+oauUeNL2iGrD3uJKyLTs383B5aapamAZrnPZVF7lZZS0zPZLCmEzZb+8WrId/5BNggAHzMemR//6Rfw3xfKnLwf3XnlENTwHyhFR/e1xBnhMETQsEKT2+3aUCl96hR9TINT5i9CvsHjWX85qXxxzzD8CNXNAbPOfvzGM/IU2OwvPeGwQe2jcOtRO8+kTNqND89+aeE+cLjBaAXoZ9oemQG/s0fjxMOJwXu/mWy0A+ZuXmzN7KX+uXhiO986Ci1CH1QKW4uJQeF7jqGzdgTCgR20kH1g9OQA1sWIQFS2EjqvlMadYyWlmEtuzs8/zeamPwO0PjLJ0yGTM5WDX+2pIEAun9Cggp9cRSIga3kqBAGJi3IZurn/BFipdSbdderfMnHrh/C60Eeps+YoxE9B9IuDNeWDsyWQKpbXsmBZJjrYuFd9/8D13mLn8xUb/6KshiZwWLot5E9FY9fc5thazvYpFs9jJLO+Pq/bcOAyaeju03IY1NJddUBZ1Sm/T4iLwD1SfPq+GOcYPP6X5yLbEVPbWZB+UJDnOBOpBGnOI1WcaimOAMKW4VKQAGQa/2PMf/RTQMzqlLT5ixigE6296jyNco/TJwAzOmm6EWYqDXk0tl1LBIi/+9UeZiUNiIubKtiomM2FwIshpP8sBubfWjDZYX3fHUIQ3tcFQ3Gwuph7Hl443dgCJreGIipP5EJAO99Qq8vDZnitmEQqpRBGTAdC4H2jPePWXj1T6YQN6jrkU4mh7QIAZSYf68sG8fa0kfaktSvNNBdbJKU4iIO8irLIrddzwrKSG5IgP7tGbvNqZ7x+4+IAp0asKsX9FaCOzonaUHY8uboPH0rGBe3acWBQNSJubW+QQrgLocRdZ2TtiAh+L+D01WkkOMcBjwve9auBgd6IjwZt/i9WE2WuRPU34C2zSo1JhcCS8Y5o4oHNWM+wdENFsOHWnlDqE191L2O/FBM9zqFPEfLZkTUgT9djJuHBhl33WH3ja4fOrRREOBni7AuCYYAPya1LCgop3/2FLzinEy99lL0bvbLjtITDbKMgQvrJjrLlj2rYG88VtLSxwFMZtXLiatgdG/xbU/cyYZn4PAhmN09ZRPAyjuwegAHF8mb2tINShw16M0E3idZwHNx9AnFMbZFN4PMl541OVZ4rHhn4Q7Aj5mgw7AWAOYcmtAbR1Whd4uy8fCqWAFvhzY9FeT548PHJiPCAdG0Rp/UzZh5FgUn2H5rPm79sTVg/etataRA36Po8O7dAW7JbhasyOKDcZO34AzQvzT36WGrSUHWmCAjtlViPk4JZ3bXLfpQZxQzKHcpEzd3xir9AGa1hL13zE+QOjTSnCEyZnIhWVgoIf7cyaW17K+OuqOuMRqgQk6qmu1R7piuGxeW6Hj+KW8CuGHudkv192W62eyYvCG+ma6Ug5yJb8BQxOOup2VwNFoE7rjHgma0HgMqk08bmtpkHcJn94abNwWCSFiBFSwz5ZQ25PqwsYP9ytsvf8NSufrHEDhlYQxbUN/rikCt8LBcnkK/eJFCuUyp2CFSuo9MZrEDQziBq9Ecgccp0y0zoNCMgobBcjfomtIA8QWRHuFZqPvzWj9JHTk3A5msZZMeb1Dlb29zYtwu653ffTLMEtJP+dFlVwj33CJJgqJV+H6pD8iHmhe4uMJh9DZ6PcW4cDgu4AH1Ri1t9VwnuR9AxcHYxVfpEW8zNEufG0Ke8tHbjcesDfCZ0ZKeYXqXTetPzs3XTXUbl40kk/jn7pLP0V0Cuym8+zS+AxrBBj51ZzL56ZtSx/6yALMeiIE6B3k7JJ2J7o7ADYl1LvqFm2o6y4gpW3I9nY+DBX2IY6RMoFvgOLjFMFbkpppB/lvUSlY1wq+3LlGytVxZNOkhVlxnpMPmf7bBx5Hy25gXXc6dDgQf0fALG/ttqv1IJoJQ8CFVM3gNYib2n067NBaTwMYPQwlQ0iBHypdiEdybetiO4qakpF/xDFh0mUiqwP0cTiSUkTS1eDElaPklnVFU8/ifPDor09IeepPFZMZ8K6Vpyhn9SqTRwr1zjNv5qHMgz38yFA+aAVlJaidxoT0vinEWCBIw/764sHWE/J1NMrv3Sc2oc/rNgd+sltKOflpC6+5Mte9LVzorwM9SaCeyALZ185QeVvkSuMIPi8gnGWsiFtdZNHoePlTcO5sNFQGssgb6VCIeWI2hH879lpWMNikMG2Fw3yXHN2X62Mt7/Bp4aqyIiuSp3OrTS4u88aHEiLVI+52MQ5FwdRSkXKgy0NZ99AXOOj4azbg+p9q4K8OyOlkPqRtBIdBxnBApKBGpHbca83wV/srCX0zKPWY1Uh4jkU3jgQuqt9R1Dvhk4MujRNmjIQwcJq7n52RewZUHRKxzKvvso+1G+3k/F8BtDy2DNizYoKTwFcuIX2JHG+OVMB2PETI7/rskQZ5VWBtXGLH4HASZBR0VPW2KRBKb80dvVZFgyK/Fp2NrDOxJRwwB9WJ20E8O07lViQxRGkQYFoYVgf4mf7s941NWF2EhH02+JZ+TAmDfZByVRc/qwgbDlEON/Cty4hYplM9AUfFdY9cwIJ10YZuMabh/QXnCaTfplDzCLqI+4pr1WphcBmEj1Rf7b78YIbAPMxdckwfN9VZtti/EvzkCVOGGQEjYG8OsIiAhwT1TmZ4Xqsl+0vaUxw3agDrWCyB2uBCCikOGZmGj4Pum0lk2/pwqWw+FPn7fWlKRS9Vpr5pyNy+WdBQ9M4wi18ewbJZcNO7Zj9t6OH3GSRxNlnHti5tFjdCgao0lOfmMmxPlcmpJxxjKT8MYF9CagFXVXQZ5KNeg557l0KFJhvAuJE9fl/j+Bdr06cf6S549CtB9Kc+iWTzHB6zwf2GBivm3CLkJM3GGqykE2QjYNakc3LLz70jEZ5U8o9y40hf6Hen2DGaBTFzTPhI2oO7oOyOkfv6r2Lom2dCzmRheQ==

cache:
  - ug4/
  
install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent
  - ps: $fileContent = "Host ug4quad`n"
  - ps: $fileContent += "        HostName        quadruped.gcsc.uni-frankfurt.de`n"
  - ps: $fileContent += "        User            gitolite3`n"
  - ps: $fileContent += "        IdentityFile    ~/.ssh/id_rsa`n"
  - ps: Set-Content $env:userprofile\.ssh\config $fileContent
  - echo quadruped.gcsc.uni-frankfurt.de,141.2.38.50 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDXtwdR4b+dC5fS8IXlB08BOIj7Fzsw4WnhSYB0/RThjkZuTSMBWasaudbN7h3/7WT4qHAgaOw0RnbiGBbDgIfoknURc4Qe/i0E/Qebz2sFIGUU6W5tvSAfl68MCD3nJVJjyD806eKfmwVlgCjN51urnyxMHewZ7VGnn2vnjWBKVAGgbHLntSR3xjwXznTnDF0w5c1I9LMN0az9bskyoS2Chc1+GTIeUWWhAbHPLGcgupB4IPcvhenUYwxewY4MjrkLkQRieVbFCazHOm1ZHnYiNAtQNu2KvdiYN3d4SQYidQcVZf19rL3VAuJOmUmuhrz7p6JJ8VcQ+08NJYHV7oX>>"c:\users\appveyor\.ssh\known_hosts"

  - appveyor DownloadFile http://mirror.olnevhost.net/pub/apache/ant/binaries/apache-ant-1.9.13-bin.zip
  - 7z x apache-ant-1.9.13-bin.zip
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\apache-ant-1.9.13\bin

  # ughub and ug4 setup 
  - if exist ughub rmdir /S /Q ughub
  - git clone https://www.github.com/UG4/ughub ughub
  
  - if not exist ug4 mkdir ug4 && echo ug4 directory was not in cache
  - cd ug4
  - if not exist .ughub ..\ughub\ughub init
  - ..\ughub\ughub addsource quadruped ug4quad:ug4-packages
  - ..\ughub\ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages.git
  - ..\ughub\ughub install ugcore ConvectionDiffusion DendriteGenerator MembranePotentialMapping Neurolucida NeuronalTopologyImporter ProMesh SkinLayerGenerator cable_neuron calciumDynamics neuro_collection

build_script:
  # build TetGen
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/NeuroBox3D/tetgen143
  - cd tetgen143
  - mkdir build
  - cd build && cmake ..\ -DCMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE=X64 -G "Visual Studio 15 2017 Win64"
  - MSBuild .\P_TETGEN.sln /property:Configuration=Release /property:Platform=x64 /m
  - mv ..\Release\tet.lib ..\
  - cd %APPVEYOR_BUILD_FOLDER%
  # tetgen is now located in %APPVEYOR_BUILD_FOLDER%\tetgen143
  
  # build ug dll
  - cd ug4
  - if not exist build mkdir build && echo build directory was not in cache
  - set ON=OFF
  - >-
    cd build && cmake ..\ -DCMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE=X64 -G "Visual Studio 15 2017 Win64" -DTARGET=vrl
    -DLAPACK=OFF -DBLAS=OFF -DDIM=ALL -DCPU=1 -DCOMPILE_INFO=ON -DEMBEDDED_PLUGINS=ON -DSTATIC_BUILD=OFF
    -DTETGEN=%APPVEYOR_BUILD_FOLDER%\tetgen143
    -DConvectionDiffusion=%ON% -DProMesh=%ON%
    -DDendriteGenerator=%ON% -DMembranePotentialMapping=%ON% -DNeuronalTopologyImporter=%ON%
    -Dcable_neuron=%ON% -DcalciumDynamics=%ON% -Dneuro_collection=%ON% -Wno-dev
  - MSBuild .\ug4.sln /property:Configuration=Release /property:Platform=x64 /m
  - cd %APPVEYOR_BUILD_FOLDER%
  # ug4.dll is now located in %APPVEYOR_BUILD_FOLDER%\ug4\bin\Release
  
  # build VRL-UG
  - git clone https://github.com/VRL-Studio/VRL-UG
  - cd ug4\bin\Release
  - if exist natives.zip rm natives.zip
  - ps: Compress-Archive -Path ug4.dll -DestinationPath natives.zip
  - cd ..\..\..
  - mkdir -p VRL-UG\src\main\resources\eu\mihosoft\vrl\plugin\content\natives\windows\x64
  - mv ug4\bin\Release\natives.zip VRL-UG\src\main\resources\eu\mihosoft\vrl\plugin\content\natives\windows\x64
  - cd VRL-UG
  - ./gradlew build
  - cd %APPVEYOR_BUILD_FOLDER%
  # VRL-UG.jar is now located in %APPVEYOR_BUILD_FOLDER%\VRL-UG\build\libs\VRL-UG.jar
  
  # build VRL-UG-API
  - git clone --depth 1 https://github.com/NeuroBox3D/build_tools.git
  - cd build_tools
  - cd consoleApp
  - mkdir -p .application\property-folder\plugins
  - cp ..\..\VRL-UG\build\libs\VRL-UG.jar .application\property-folder\plugins
  - call run.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  # VRL-UG-API.jar is now located in %APPVEYOR_BUILD_FOLDER%\build_tools\consoleApp\.application\property-folder\plugin-updates

  # build VRL
  - git clone https://github.com/VRL-Studio/VRL
  - cd VRL\VRL
  - ant jar
  - cd %APPVEYOR_BUILD_FOLDER%
  # VRL.jar is now located in %APPVEYOR_BUILD_FOLDER%\VRL\VRL\dist
  
  # build VRL-UserData
  - git clone https://github.com/VRL-Studio/VRL-UserData
  - cd VRL-UserData
  - mklink /h jars\VRL.jar ..\VRL\VRL\dist\VRL.jar
  - mklink /h jars\VRL-UG.jar ..\VRL-UG\build\libs\VRL-UG.jar
  - mklink /h jars\VRL-UG-API.jar ..\build_tools\consoleApp\.application\property-folder\plugin-updates\VRL-UG-API.jar
  - ant jar
  - cd %APPVEYOR_BUILD_FOLDER%
  # VRL-UserData.jar is now located in %APPVEYOR_BUILD_FOLDER%\VRL-UserData\dist\VRL-UserData.jar

  # build VRL-NeuroBox
  - git clone https://github.com/NeuroBox3D/VRL-NeuroBox-Plugin.git
  - cd VRL-NeuroBox-Plugin
  - mkdir lib
  - mklink /h lib\VRL-UG.jar ..\VRL-UG\build\libs\VRL-UG.jar
  - mklink /h lib\VRL-UG-API.jar ..\build_tools\consoleApp\.application\property-folder\plugin-updates\VRL-UG-API.jar
  - mklink /h lib\VRL-UserData.jar ..\VRL-UserData\dist\VRL-UserData.jar
  - ./gradlew build
  - cd %APPVEYOR_BUILD_FOLDER%
  # VRL-NeuroBox-Plugin.jar is now located in %APPVEYOR_BUILD_FOLDER%\VRL-NeuroBox-Plugin\build\libs\VRL-UG.jar

artifacts:
  - path: VRL-UG\build\libs\VRL-UG.jar
    name: UGjar
  - path: build_tools\consoleApp\.application\property-folder\plugin-updates\VRL-UG-API.jar
    name: UGAPIjar
  - path: VRL-UserData\dist\VRL-UserData.jar
    name: UserDatajar
  - path: VRL-NeuroBox-Plugin\build\libs\VRL-NeuroBox-Plugin.jar
    name: NeuroBoxjar

deploy:
  description: 'test'
  provider: GitHub
  auth_token:
    secure: Ki/Fm5IhIlggsa+Yu/cuZGBu0gmfhmY50/dgFDkSbFGg/xx1UyI1fhXduHmlsOqH
  draft: true
  prerelease: true
  artifact: UGjar, UGAPIjar, UserDatajar, NeuroBoxjar


